version: "3.8"

# usage: `docker compose up` or `docker compose up --detach`
services:
  notebook-image:
    build:
      context: .
      dockerfile: notebook.Dockerfile
      args:
        FORK: ${FORK:-vyperlang}
        REF: ${REF:-master}
    image: titanoboa-notebook
    command: ["echo", "This image is started by Jupyter"]

  vypyter:
    build:
      context: .
      dockerfile: jupyterhub.Dockerfile
    depends_on:
      - notebook-image
    restart: always
    volumes:
      # The JupyterHub configuration file
      - "./config/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host for docker-in-docker
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "./data:/data"

    image: jupyterhub
    # for child processes to connect to
    container_name: jupyterhub
    networks:
      - jupyterhub-network

    ports:
      - "${PORT:-8000}:8000"

    env_file: .env
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: titanoboa-notebook
      # Using this run command
      DOCKER_SPAWN_CMD: start-singleuser.sh
      # weird things happen when nesting docker containers
      # pass the directory on the host to mount on the inner container
      PWD: "${PWD}"

networks:
  jupyterhub-network:
    name: jupyterhub-network
