name: Deploy to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment
        default: stable

jobs:
  deploy:
    name: "Deploy to ${{ inputs.environment }}"
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we cannot push without the history
      - name: Setup SSH
        uses: ./.github/workflows/setup-ssh
        with:
          ssh-key: ${{ secrets.AUTH_SSH_KEY }}
          username: ${{ secrets.AUTH_SSH_USER }}
          host-key: ${{ vars.HOST_PUBLIC_KEY }}
          host-name: ${{ vars.HOST }}
      - name: Run command
        shell: bash
        run: |
            git push --force try_vyper:${{ vars.REPO_DIR }}/
            ssh try_vyper bash <<EOF
            cd ${{ vars.REPO_DIR }}
            # set env vars inside the SSH session
            export REF=${{ vars.BOA_COMMIT_ISH }}
            export PORT=${{ vars.PORT }}
            export JUPYTERHUB_IMAGE_NAME=${{ vars.JUPYTERHUB_IMAGE_NAME }}
            export NOTEBOOK_IMAGE_NAME=${{ vars.NOTEBOOK_IMAGE_NAME }}
            ./full_reload.sh
            EOF
