name: Restart

on:
  schedule:
    # Run every day at 5:00 UTC
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment
        default: stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Restart ${{ inputs.environment }}"

    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        uses: ./.github/workflows/setup-ssh
        with:
          ssh-key: ${{ secrets.AUTH_SSH_KEY }}
          username: ${{ secrets.AUTH_SSH_USER }}
          host-key: ${{ vars.HOST_PUBLIC_KEY }}
          host-name: ${{ vars.HOST }}
      - name: Run command
        shell: bash
        run: |
            ssh try_vyper bash <<EOF
            cd ${{ vars.REPO_DIR }}
            docker compose down
            docker compose up --detach
            EOF
