name: restart

on:
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment
        default: stable

jobs:
  deploy:
    name: "Restart ${{ inputs.environment }}"
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        uses: ./.github/workflows/setup-ssh
        with:
          ssh-key: ${{ secrets.AUTH_SSH_KEY }}
          username: ${{ secrets.AUTH_SSH_USER }}
          host-key: ${{ vars.HOST_PUBLIC_KEY }}
          host-name: ${{ vars.HOST }}
      - name: Run command
        shell: bash
        run: |
            ssh try_vyper bash <<EOF
            cd ${{ vars.REPO_DIR }}
            docker compose down
            docker compose up --detach
            EOF
