name: Update ${{ inputs.environment }}

on:
  schedule:
    # Run Monday at 4:00 UTC
    - cron: "0 4 * * 1"
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment
        default: stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Upgrade dependencies"

    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        uses: ./.github/workflows/setup-ssh
        with:
          ssh-key: ${{ secrets.AUTH_SSH_KEY }}
          username: ${{ secrets.AUTH_SSH_USER }}
          host-key: ${{ vars.HOST_PUBLIC_KEY }}
          host-name: ${{ vars.HOST }}
      - name: Run command
        shell: bash
        run: |
            ssh try_vyper bash <<EOF
            apt-get update
            apt-get upgrade -y
            docker system prune --force --all --volumes
            EOF
